name: License Check

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Licensebat
        uses: licensebat/licensebat-action@v1
        with:
          dependency-file-path: 'package-lock.json'